const API_BASE = '/api'

export async function generateArchitecture(idea) {
  const res = await fetch(`${API_BASE}/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ idea }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail || 'Failed to generate architecture')
  }
  return res.json()
}

export async function getProjects() {
  const res = await fetch(`${API_BASE}/projects`)
  if (!res.ok) throw new Error('Failed to load projects')
  return res.json()
}

export async function getProject(id) {
  const res = await fetch(`${API_BASE}/projects/${id}`)
  if (!res.ok) throw new Error('Project not found')
  return res.json()
}

export async function deleteProject(id) {
  const res = await fetch(`${API_BASE}/projects/${id}`, { method: 'DELETE' })
  if (!res.ok) throw new Error('Failed to delete project')
  return res.json()
}

export function exportToJSON(blueprint, projectName) {
  const data = JSON.stringify(blueprint, null, 2)
  const blob = new Blob([data], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(projectName || 'blueprint').replace(/\s+/g, '_').toLowerCase()}_blueprint.json`
  a.click()
  URL.revokeObjectURL(url)
}

export function exportToMarkdown(blueprint, projectName) {
  const bp = blueprint
  let md = `# ${bp.project?.name || projectName || 'Software Architecture Blueprint'}\n\n`
  md += `> Generated by AI Software Architect\n\n`
  md += `---\n\n`

  // Project Overview
  md += `## Project Overview\n\n`
  md += `| Field | Value |\n|-------|-------|\n`
  md += `| **Name** | ${bp.project?.name || 'N/A'} |\n`
  md += `| **Type** | ${bp.project?.type || 'N/A'} |\n`
  md += `| **Complexity** | ${bp.project?.complexity || 'N/A'} |\n`
  md += `| **Target Users** | ${bp.project?.target_users?.join(', ') || 'N/A'} |\n\n`
  md += `${bp.project?.description || ''}\n\n`

  // Functional Requirements
  md += `## Functional Requirements\n\n`
  if (bp.requirements?.functional?.length) {
    md += `| ID | Title | Description | Priority |\n|-----|-------|-------------|----------|\n`
    bp.requirements.functional.forEach((r) => {
      md += `| ${r.id} | ${r.title} | ${r.description} | ${r.priority} |\n`
    })
  }
  md += `\n`

  // Non-Functional Requirements
  md += `## Non-Functional Requirements\n\n`
  if (bp.requirements?.non_functional?.length) {
    md += `| ID | Category | Description | Priority |\n|-----|----------|-------------|----------|\n`
    bp.requirements.non_functional.forEach((r) => {
      md += `| ${r.id} | ${r.category} | ${r.description} | ${r.priority} |\n`
    })
  }
  md += `\n`

  // Architecture
  md += `## Architecture\n\n`
  md += `**Pattern:** ${bp.architecture?.pattern || 'N/A'}\n\n`
  md += `**Reason:** ${bp.architecture?.reason || 'N/A'}\n\n`
  if (bp.architecture?.mermaid_diagram) {
    md += "```mermaid\n" + bp.architecture.mermaid_diagram + "\n```\n\n"
  }

  // Tech Stack
  md += `## Technology Stack\n\n`
  const stackCategories = ['frontend', 'backend', 'database', 'authentication', 'deployment', 'other']
  stackCategories.forEach((cat) => {
    const items = bp.tech_stack?.[cat]
    if (items?.length) {
      md += `### ${cat.charAt(0).toUpperCase() + cat.slice(1)}\n\n`
      items.forEach((t) => {
        md += `- **${t.name}**: ${t.reason}\n`
      })
      md += `\n`
    }
  })

  // Database
  md += `## Database Schema\n\n`
  if (bp.database?.entities?.length) {
    bp.database.entities.forEach((e) => {
      md += `### ${e.name}\n\n`
      md += `${e.description || ''}\n\n`
      md += `| Field | Type | Constraints |\n|-------|------|-------------|\n`
      e.fields?.forEach((f) => {
        md += `| ${f.name} | ${f.type} | ${f.constraints?.join(', ') || '-'} |\n`
      })
      md += `\n`
    })
  }

  // APIs
  md += `## API Endpoints\n\n`
  md += `| Method | Endpoint | Purpose | Auth |\n|--------|----------|---------|------|\n`
  bp.apis?.forEach((a) => {
    md += `| ${a.method} | \`${a.endpoint}\` | ${a.purpose} | ${a.auth_required ? 'Yes' : 'No'} |\n`
  })
  md += `\n`

  // Modules
  md += `## Modules\n\n`
  bp.modules?.forEach((m) => {
    md += `### ${m.name}\n\n`
    md += `**Purpose:** ${m.purpose}\n\n`
    md += `**Responsibilities:**\n`
    m.responsibilities?.forEach((r) => { md += `- ${r}\n` })
    md += `\n`
  })

  // Security
  md += `## Security Recommendations\n\n`
  md += `| Concern | Recommendation | Priority |\n|---------|---------------|----------|\n`
  bp.security?.forEach((s) => {
    md += `| ${s.concern} | ${s.recommendation} | ${s.priority} |\n`
  })
  md += `\n`

  // Quality Score
  md += `## Quality Score\n\n`
  md += `| Metric | Score |\n|--------|-------|\n`
  md += `| Scalability | ${bp.quality_score?.scalability}/100 |\n`
  md += `| Security | ${bp.quality_score?.security}/100 |\n`
  md += `| Maintainability | ${bp.quality_score?.maintainability}/100 |\n`
  md += `| Performance | ${bp.quality_score?.performance}/100 |\n`
  md += `| **Overall** | **${bp.quality_score?.overall}/100** |\n\n`

  // Roadmap
  md += `## Development Roadmap\n\n`
  bp.roadmap?.forEach((phase) => {
    md += `### ${phase.phase}: ${phase.title} (${phase.duration})\n\n`
    phase.tasks?.forEach((t) => {
      md += `- [ ] ${t.task} (${t.duration})\n`
    })
    md += `\n`
  })

  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(projectName || 'blueprint').replace(/\s+/g, '_').toLowerCase()}_blueprint.md`
  a.click()
  URL.revokeObjectURL(url)
}
